name: CJoy Beauty
favicon: null
layout_spectrum: 0.13784336484968662
typography_spectrum: 0.7760583071503788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7407526664901525
  lightness: 0.720294929575175
  saturation: 0.0864946492947638
  rhythmicContrast: 0.5744425274897367
purpose: []
