typography_spectrum: 0.79368
color:
  brandColors:
    - '#c4e1fb'
    - '#c50a75'
    - '#12121d'
    - '#717689'
    - '#899ebb'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.40506
analytics:
  google: null
  facebook: null
  twitter: null
name: CJoy Beauty
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
