name: CJoy Beauty
favicon: null
layout_spectrum: 0.40506
typography_spectrum: 0.79368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4e1fb'
    - '#c50a75'
    - '#12121d'
    - '#717689'
    - '#899ebb'
  brandStrength: 0.7407526664901525
  lightness: 0.720294929575175
  saturation: 0.0864946492947638
  rhythmicContrast: 0.5744425274897367
purpose: []
